spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  logging:
    level:
      org.springframework: INFO
      org.springframework.web: DEBUG
