spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  logging:
    level:
      org.springframework: INFO
      org.springframework.web: DEBUG
keycloak:
  realm: spring-realm
  resource: spring-app
  auth-server-url: http://localhost:8180/auth
  ssl-required: external
  public-client: true
  principal-attribute: preferred_username

